config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'articles/index'

  resources :articles

  resources :controladoras do
  	resources :almacens do
  		resources :productos do
  			resources :formulas do
  				resources :costo_indirectos
  				resources :materials do
  					resources :costos
  				end
  			end
  		end
  		resources :materials do
  			resources :costos
  		end
  	end
  	resources :proveedors do
  		resources :materials do
  			resources :costos
  		end
  	end
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/almacen.rb
class Almacen < ApplicationRecord
	belongs_to :controladora
	has_many :productos, dependent: :destroy
	has_many :materials, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/controladora.rb
class Controladora < ApplicationRecord
	has_one :almacen, dependent: :destroy
	has_many :proveedors, dependent: :destroy

  def exists?
    true
  end
end

app/models/costo.rb
class Costo < ApplicationRecord
  belongs_to :material
end

app/models/costo_indirecto.rb
class CostoIndirecto < ApplicationRecord
  belongs_to :formula
end

app/models/formula.rb
class Formula < ApplicationRecord
	belongs_to :producto
	has_many :costo_indirectos, dependent: :destroy
	has_many :materials, dependent: :destroy
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :almacen
  belongs_to :proveedor
  has_many :costos
end

app/models/producto.rb
class Producto < ApplicationRecord
  belongs_to :almacen
  has_one :formula, dependent: :destroy
end

app/models/proveedor.rb
class Proveedor < ApplicationRecord
  belongs_to :controladora
  has_many :materials, dependent: :destroy
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  end

  def index
  	@articles = Article.all
  end

  def show
  	@article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
   
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
   
  def update
    @article = Article.find(params[:id])
   
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
   
    redirect_to articles_path
  end
   
  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/costos_controller.rb
class CostosController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/almacens_helper.rb
module AlmacensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/controladoras_helper.rb
module ControladorasHelper
end

app/helpers/costos_helper.rb
module CostosHelper
end

app/helpers/formulas_helper.rb
module FormulasHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= form_with(model: @article, local: true) do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>


  <div>
    <%= link_to 'New article', new_article_path %>
  </div>
  <div>
    <%= link_to 'Back', welcome_index_path %>
  </div>
  
</table>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>

  
<%= link_to 'Back', articles_path %>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', articles_path %>
<%= link_to 'Destroy', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %>