config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'articles/index'

  resources :articles

  resources :controladoras do
  	resources :almacens do
  		resources :productos do
  			resources :formulas do
  				resources :costo_indirectos
  				resources :materials do
  					resources :costos
  				end
  			end
  		end
  		resources :materials do
  			resources :costos
  		end
  	end
  	resources :proveedors do
  		resources :materials do
  			resources :costos
  		end
  	end
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/almacen.rb
class Almacen < ApplicationRecord
	belongs_to :controladora
	has_many :productos, dependent: :destroy
	has_many :materials, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/controladora.rb
class Controladora < ApplicationRecord
	has_one :almacen, dependent: :destroy
	has_many :proveedors, dependent: :destroy

  def exists?
    true
  end
end

app/models/costo.rb
class Costo < ApplicationRecord
  belongs_to :material
end

app/models/costo_indirecto.rb
class CostoIndirecto < ApplicationRecord
  belongs_to :formula
end

app/models/formula.rb
class Formula < ApplicationRecord
	belongs_to :producto
	has_many :costo_indirectos, dependent: :destroy
	has_many :materials, dependent: :destroy
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :almacen
  belongs_to :proveedor
  has_many :costos
end

app/models/producto.rb
class Producto < ApplicationRecord
  belongs_to :almacen
  has_one :formula, dependent: :destroy
end

app/models/proveedor.rb
class Proveedor < ApplicationRecord
  belongs_to :controladora
  has_many :materials, dependent: :destroy
end

app/controllers/costos_controller.rb
class CostosController < ApplicationController
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
	def new
		@controladora = Controladora.find(1)
	end

	def index
		@productos = Productos.all
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/almacens_helper.rb
module AlmacensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/controladoras_helper.rb
module ControladorasHelper
end

app/helpers/costos_helper.rb
module CostosHelper
end

app/helpers/formulas_helper.rb
module FormulasHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/productos/new.html.erb
<%= form_with scope: :producto, url: controladora_almacen_productos_path(@controladora, @controladora.almacen), local: true do |form| %>
  <p>
    <%= form.label :nombre %><br>
    <%= form.text_field :nombre %>
  </p>

  <p>
    <%= form.label :porcentaje_ganancia %><br>
    <%= form.text_field :porcentaje_ganancia %>
  </p>

  <table>

    <tr>
      <th>Codigo</th>
      <th>Nombre</th>
      <th></th>
    </tr>
    <% @controladora.almacen.materials.each do |material| %>
      <tr>
        <td>
          <%= material.codigoMaterial %>
        </td>
        <td>
          <%= material.nombre %>
        </td>
      </tr>
    <% end %>
  <table>

  <p>
    <%= form.label :materiales %><br>
    <%= form.text_field :materiales %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>

  
<%= link_to 'Back', controladora_almacen_productos_path(@controladora, @controladora.almacen) %>
<% end %>