config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'articles/index'

  resources :articles

  resources :controladoras do
  	resources :almacens do
  		resources :productos do
  			resources :formulas do
  				resources :costo_indirectos
  				resources :materials do
  					resources :costos
  				end
  			end
  		end
  		resources :materials do
  			resources :costos
  		end
  	end
  	resources :proveedors do
  		resources :materials do
  			resources :costos
  		end
  	end
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/almacen.rb
class Almacen < ApplicationRecord
	belongs_to :controladora
	has_many :productos, dependent: :destroy
	has_many :materials, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/controladora.rb
class Controladora < ApplicationRecord
	has_one :almacen, dependent: :destroy
	has_many :proveedors, dependent: :destroy

  def exists?
    true
  end
end

app/models/costo.rb
class Costo < ApplicationRecord
  belongs_to :material
end

app/models/costo_indirecto.rb
class CostoIndirecto < ApplicationRecord
  belongs_to :formula
end

app/models/formula.rb
class Formula < ApplicationRecord
	belongs_to :producto
	has_many :costo_indirectos, dependent: :destroy
	has_many :materials, dependent: :destroy
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :almacen
  belongs_to :proveedor
  has_many :costos
end

app/models/producto.rb
class Producto < ApplicationRecord
  belongs_to :almacen
  has_one :formula, dependent: :destroy
end

app/models/proveedor.rb
class Proveedor < ApplicationRecord
  belongs_to :controladora
  has_many :materials, dependent: :destroy
end

app/controllers/costos_controller.rb
class CostosController < ApplicationController
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
	def new
	end

	def index
		@controladora = Controladora.find(1)
	end

	def create
		article_params[:cantidadDisponible] = article_params[:cantidadDisponible].to_f
		article_params[:fechaDeVencimiento] = article_params[:fechaDeVencimiento].to_date()
		
		@controladora = Controladora.find(1)
		@almacen = @controladora.almacen
		@material = @almacen.materials.create(article_params)
		@controladora.save

		render 'new'
	end

	private
	    def article_params
	      params.require(:material).permit(:idMaterial, :codigoMaterial, :nombre, :descripcion, :estatus, :cantidadDisponible, :unidadDeMedida, :fechaDeVencimiento)
	    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/almacens_helper.rb
module AlmacensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/controladoras_helper.rb
module ControladorasHelper
end

app/helpers/costos_helper.rb
module CostosHelper
end

app/helpers/formulas_helper.rb
module FormulasHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/materials/index.html.erb
<h1>Listing materials</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
 
  <% @controladora.almacen.materials.each do |material| %>
    <tr>
      <td><%= material.codigo %></td>
      <td><%= material.nombre %></td>
      <td><%= link_to 'Show', controladora_almacen_material_path(material) %></td>
    </tr>
  <% end %>


  <div>
    <%= link_to 'New material', new_controladora_almacen_material_path %>
  </div>
  <div>
    <%= link_to 'Back', welcome_index_path %>
  </div>
  
</table>

app/views/materials/new.html.erb
<%= form_with scope: :material, url: controladora_almacen_materials_path(1, 1), local: true do |form| %>
  <p>
    <%= form.label :idMaterial %><br>
    <%= form.text_field :idMaterial %>
  </p>

  <p>
    <%= form.label :codigoMaterial %><br>
    <%= form.text_field :codigoMaterial %>
  </p>
 
  <p>
    <%= form.label :nombre %><br>
    <%= form.text_area :nombre %>
  </p>
 
  <p>
    <%= form.label :descripcion %><br>
    <%= form.text_area :descripcion %>
  </p>
 
  <p>
    <%= form.label :estatus %><br>
    <%= form.text_area :estatus %>
  </p>
 
  <p>
    <%= form.label :cantidadDisponible %><br>
    <%= form.text_area :cantidadDisponible %>
  </p>
 
  <p>
    <%= form.label :unidadDeMedida %><br>
    <%= form.text_area :unidadDeMedida %>
  </p>
 
  <p>
    <%= form.label :fechaDeVencimiento %><br>
    <%= form.text_area :fechaDeVencimiento %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>

  <div>
    <%= @material.idMaterial %>
  </div>

  
<%= link_to 'Back', controladora_almacen_materials_path(1, 1) %>
<% end %>